### ISSUE TITLE
Pls make cli version.

### ISSUE THREAD

**Issue by WisnuNug** [lybell-art/xnb-js#9]
Hello, I really like your work! You are the best!. But can you make a CLI version for Windows like the Leonblade version? Because I'm more comfortable with CLI.It's more efficient for me too. But if it's specifically for the web, that's not a problem. Thank You.

**Comment by lybell-art** [comment]
Thank you for your interest in xnb.js! xnb.js is designed to be **compatible with both browsers and node.js** by default, so **you can create cli applications that run on node.js using xnb.js**.
To import the xnb.js library from node.js, use `npm install xnb`. The plug-in dealing with the custom class of stardew valley has not been deployed yet, so download it directly from this repository.

But **I don't intend to create xnb cli converter myself**. There are already cli applications (xnbcli, xnbextractor) dealing with xnb (but they failed to unpack custom xnb data added in stardew valley 1.4 or later), so I decided I didn't need to create another xnb cli converter.

**Comment by WisnuNug** [comment]
Thanks you ❤️
